name: approachable_geek
description: "Coding Project for Approachable Geeks by John Patrick Prieto"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  auto_route: ^11.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  image_picker: ^1.2.1
  injectable: ^2.7.1+4
  intl: ^0.20.2
  json_annotation: ^4.10.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
  generate: true'

  assets:
    - assets/images/
    - assets/data/
