name: approachable_geek
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  intl: ^0.20.2
  json_annotation: ^4.10.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
  generate: true
